name: Audit
run-name: ${{ github.actor }} is auditing source code on GitHub Actions 🚀
on: [push]
jobs:
  "Get Python Version":
    id: get-python-version
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
