name: Audit

run-name: ${{ github.actor }} -> Audit Source Code 🚀

on: [push]

jobs:

  get-python-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: get-python-version
        run: 'echo "PYTHON_VERSION=$(cat .python-version)" >> ${GITHUB_OUTPUT}'
      - run: 'echo "PYTHON_VERSION=$(cat .python-version)"'
    outputs:
      PYTHON_VERSION: ${{ steps.get-python-version.outputs.PYTHON_VERSION }}

  pre-commit:
    needs:
      - get-python-version
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/docker/library/python:${{ needs.get-python-version.outputs.PYTHON_VERSION }}-slim
    permissions:
      contents: read
    steps:
      - run: |
          apt-get update
          apt-get install -y git
          pip install -U pip
          pip install -U setuptools poetry pre-commit
          echo "Disabling git safe directory"
          git config --global --add safe.directory '*'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ github.ref }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.venv
          key: venv-cache-${{ github.ref }}
      - run: poetry install --only dev
      - run: pre-commit run -a
